# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required

before_install:
  - tlmgr install index
    #- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

    #install:
  #  - sudo apt-get install -qq g++-4.9

addons:
  apt:
    packages:
      - libxml2-dev
      - g++
#      libv8-3.14-dev
language: r
r:
  - release
  - devel
  - 3.2.4
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr
r_packages:
  - xml2
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d30a16d1ede5c5bf507d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email: false
