# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
cache: packages

# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing hunspell installation to fail
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
  - tlmgr install index

# The git config settings are not setup on travis by default
before_script:
    - git config --global user.name "travis"
    - git config --global user.email "travis@example.org"

addons:
  apt:
    packages:
      - libxml2-dev
#      libv8-3.14-dev

r:
  - release
  - devel
  - 3.2.4

r_github_packages:
  - jimhester/covr

r_packages:
  - xml2

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::coveralls()'

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d30a16d1ede5c5bf507d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email: true
