# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1' 

install:
  ps: |
        Bootstrap

# Adapt as necessary starting from here

cache:
  - C:\RLibrary

environment:
  global:
      WARNINGS_ARE_ERRORS: 1
      USE_RTOOLS: true

  matrix:
    - R_VERSION: devel
      R_ARCH: x64
      GCC_PATH: mingw_64

    - R_VERSION: release
      R_ARCH: x64
      GCC_PATH: mingw_64

    - R_VERSION: release
      R_ARCH: i386
      GCC_PATH: mingw_32

    - R_VERSION: 3.2.5
      R_ARCH: x64
      RTOOLS_VERSION: 32

build_script:
  #- travis-tool.sh install_github hadley/devtools
  - travis-tool.sh install_deps
  - travis-tool.sh install_r knitr
  - travis-tool.sh install_r testthat
  - travis-tool.sh install_r covr,
  - travis-tool.sh install_r knitr,
  - travis-tool.sh install_r DiagrammeR,
  - travis-tool.sh install_r iterators,
  - travis-tool.sh install_r foreach,
  - travis-tool.sh install_r tools
  - travis-tool.sh install_r DiagrammeRsvg
  - travis-tool.sh install_r microbenchmark
  - travis-tool.sh install_r rmarkdown
  - travis-tool.sh install_r doParallel

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

version: 0.0.0.9001.{build}

build:
  verbosity: normal

notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
