#!/bin/sh

rm -f  aclocal.m4 \
       src/config.h \
       config.status config.log \
       src/Makevars \
       src/autoloads.h src/ldflags.txt  \
       src/r src/gitversion.h *~ *.o \
       src/*.o \
       src/*.so \
       stamp-h1
rm -rf autom4te.cache .deps inst/bin/
