# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_tree <- function(id, data) {
    .Call('GeneralTree_initialize_tree', PACKAGE = 'GeneralTree', id, data)
}

pass_gti_xptr <- function(gti) {
    .Call('GeneralTree_pass_gti_xptr', PACKAGE = 'GeneralTree', gti)
}

cmp <- function(gti_lhs, gti_rhs) {
    .Call('GeneralTree_cmp', PACKAGE = 'GeneralTree', gti_lhs, gti_rhs)
}

add_node <- function(gti_sexp, parent_id, id, data) {
    .Call('GeneralTree_add_node', PACKAGE = 'GeneralTree', gti_sexp, parent_id, id, data)
}

