# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_child <- function(gti, parent_id, id, data) {
    invisible(.Call('GeneralTree_add_child', PACKAGE = 'GeneralTree', gti, parent_id, id, data))
}

initialize_tree <- function(id, data) {
    .Call('GeneralTree_initialize_tree', PACKAGE = 'GeneralTree', id, data)
}

