# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_tree <- function(id, data) {
    .Call('GeneralTree_initialize_tree', PACKAGE = 'GeneralTree', id, data)
}

pass_gti_xptr <- function(gti) {
    .Call('GeneralTree_pass_gti_xptr', PACKAGE = 'GeneralTree', gti)
}

cmp <- function(gti_lhs, gti_rhs) {
    .Call('GeneralTree_cmp', PACKAGE = 'GeneralTree', gti_lhs, gti_rhs)
}

add_node <- function(gti_sexp, parent_id, id, data) {
    .Call('GeneralTree_add_node', PACKAGE = 'GeneralTree', gti_sexp, parent_id, id, data)
}

get_value <- function(gti_sexp, key) {
    .Call('GeneralTree_get_value', PACKAGE = 'GeneralTree', gti_sexp, key)
}

get_children_keys <- function(gti_sexp, parent_id) {
    .Call('GeneralTree_get_children_keys', PACKAGE = 'GeneralTree', gti_sexp, parent_id)
}

get_siblings_keys <- function(gti_sexp, node_id) {
    .Call('GeneralTree_get_siblings_keys', PACKAGE = 'GeneralTree', gti_sexp, node_id)
}

get_children_values <- function(gti_sexp, parent_id) {
    .Call('GeneralTree_get_children_values', PACKAGE = 'GeneralTree', gti_sexp, parent_id)
}

get_siblings_values <- function(gti_sexp, node_id) {
    .Call('GeneralTree_get_siblings_values', PACKAGE = 'GeneralTree', gti_sexp, node_id)
}

